---
title: "&nbsp;"
output:
  html_document:
    theme: yeti
    highlight: textmate
    css: [../../css/Research.css, ../../css/navbar.css, ../../css/body.css]
    includes:
      in_header: ../../heros/Research_hero.html
      after_body: ../../footer.html
---

<style>
h1 {text-align: center !important; 
   font-weight: bold !important; 
   font-size: 36px !important;
   line-height: 1.5em;}
   
h2 {font-weight: bold !important;} 
   
.External_link{
  border-radius: 5px;
  border: none;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  width: 60px;
}

</style>

<div>
# Active ant hitchhiking on vehicles and its ecological implications
</div>

<br>

## Project Summary
<div style="height: 0.25em;"></div>

Transportation technologies have made the world more connected than ever. We use all sorts of transportation objects in our everyday life. But besides humans, many organisms (e.g., plant seeds, insects, and microbes) can take advantage of the transportation systems and travel to a new place. This is concerning because it facilitates the long-distance dispersal of organisms, allowing increased probabilities of biological invasions. 

<div style="height: 1em;"></div>

Over the past few years, people in Taiwan have been reporting their cars and scooters being colonized by groups of ants. This is special because the ants are actively moving onto the motor vehicles instead of passively or accidentally being carried by vehicles. To dive deeper into this interesting "hitchhiking" phenomenon, we collected citizen science data from Facebook and asked the vehicle owners to provide detailed information on the hitchhiking events along with a photo of the ants. From 2017 to 2023, we got a total of 52 cases of ant hitchhiking on vehicles from nine ant species. At least three cases had queen(s) and another eight cases had brood. Out of the nine species, seven were exotic/invasive. Moreover, arboreal or semi-arboreal ant species, particularly the exotic black
cocoa ant (_Dolichoderus thoracicus_), accounted for the majority of the reported cases. Finally, more cases were reported in the warmer seasons (spring and summer) than in the colder seasons (fall and winter).

<div style="height: 1em;"></div>

With our analyses, we identified at least three key factors for a successful ant hitchhiking event:

1. Searching ability: Of course, ants need to encounter a vehicle before they can even hitchhike, and this largely depends on their searching/exploratory behavior. Ants are generally more active under warmer conditions, and we indeed found that there were more hitchhiking cases reported in spring and summer compared to fall and winter. Moreover, arboreal ants typically exhibit frequent foraging activities and territorial patrolling around their nesting trees, which may increase their chance of vehicle encounter.

2. Climbing ability: Ants need to climb or hold onto the vehicle after locating it. The metallic paint on the vehicle surface is slippery, and only species with good climbing/gripping ability are able to hitchhike. The climbing and moving performance of ants is determined by the morphological characteristics of leg segments. Arboreal ants have hooked pretarsal claws, well-developed adhesive pads, and fine tarsal hairs, all of which allow them to walk on smooth vertical substrates.

3. Thermal tolerance: The temperature on the surface and in the interior of the vehicle can increase dramatically when exposed to sunlight, especially in the summer. This suggests that the thermal tolerance of hitchhiking species may play an important role in determining their colonization success. Arboreal ants are generally more heat- and drought-tolerant than ground-dwelling ants are, and therefore they have a greater probability of successfully hitchhiking on vehicles.

<div style="height: 1em;"></div>

To our knowledge, this study represents the first effort to profile active ant hitchhiking on vehicles. We encourage future studies to examine the abiotic and biotic factors that determine the success of hitchhiking events to better predict the spread of exotic/invasive ants and to develop effective management strategies for preventing their biological invasions.

<br>

## Publication
<div style="height: 0.25em;"></div>

<p>Hsu, F-C.^†^, <b><u>G-C. Hsu</u></b>^†^, C-C. Lee, C-C. Lin, C-K. Ho, and C-C. Scotty Yang. 2024. Free ride without raising a thumb: A citizen science project reveals the pattern of active ant hitchhiking on vehicles and its ecological implications. <i>**Ecological Entomology**</i> 1–5. <a href="https://doi.org/10.1111/een.13336" target="_blank"> https://doi.org/10.1111/een.13336</a> (^†^Co-first authors)</p>


