---
title: "&nbsp;"
output:
  html_document:
    theme: yeti
    highlight: textmate
    css: [../../css/Research.css, ../../css/navbar.css, ../../css/body.css]
    includes:
      in_header: ../../heros/Research_hero.html
      after_body: ../../footer.html
---

<style>
h1 {text-align: center !important; 
   font-weight: bold !important; 
   font-size: 36px !important;
   line-height: 1.5em;}
   
h2 {font-weight: bold !important;} 
   
.External_link{
  border-radius: 5px;
  border: none;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  width: 60px;
}

#project-summary {
 width: 115%; margin-left: -50px;
}

#publication {
 width: 115%; margin-left: -50px;
}

</style>

<div style="width: 115%; margin-left: -50px;">
# An experimental framework for quantifying the degree of intraguild predation in omnivorous food webs in the field
</div>

<br>

## Project Summary
<div style="height: 0.25em;"></div>

Intraguild predation (IGP) is ubiquitous in natural and human-managed systems and plays a critical role in food web dynamics. Studies have documented the occurrence of IGP across a wide range of predator taxa. However, to better understand the effect of IGP on species population dynamics, we also need to know its degree/intensity (i.e., the proportion [in number] of mesopredators consumed in the total diet [shared prey + mesopredator] of top predators), which receives little attention in past research.

<div style="height: 1em;"></div>

To fill this gap, I propose an experimental framework that combines controlled feeding trials and stable isotope analysis to quantify the degree of IGP in an omnivorous food web in the field. In this framework, two rounds of feeding trials along with stable isotope analysis are first used to construct a standard curve of the relationship between the diet composition of top predator (e.g., the degree of IGP) and its nitrogen isotope signatures. Then the nitrogen isotope signatures of field-collected top predator individuals are analyzed and interpolated to the standard curve to estimate the degree of IGP in the field. 

<div style="height: 1em;"></div>

The framework leverages the strengths of different experimental approaches to studying trophic interactions: Controlled feeding trials minimize the confounding effects of non-focal species on the interactions between focal organisms; stable isotope analysis of field samples allows for trophic interactions under natural settings. Therefore, the framework provides a useful tool for quantifying IGP in a more accurate and realistic fashion. Furthermore, the current framework can potentially be extended to food webs involving more complex interactions (e.g., multiple shared prey and cannibalism) and complemented with other approaches (e.g., molecular gut content analysis) to capture a more complete picture of IGP dynamics in the field.

<br>

## Publication
<div style="height: 0.25em;"></div>

<p><b><u>Hsu, G-C.</u></b> 2023. An experimental framework for quantifying the degree of intraguild predation in omnivorous food webs in the field. <i>**Journal of Zoology**</i> 320: 1-6.
<a href="https://doi.org/10.1111/jzo.13050" target="_blank"> https://doi.org/10.1111/jzo.13050</a></p>


