---
title: "&nbsp;"
output:
  html_document:
    theme: yeti
    highlight: textmate
    css: [../../css/Research.css, ../../css/navbar.css, ../../css/body.css]
    includes:
      in_header: ../../heros/Research_hero.html
      after_body: ../../footer.html
---

<style>
h1 {text-align: center !important; 
   font-weight: bold !important; 
   font-size: 36px !important;
   line-height: 1.5em;}
   
h2 {font-weight: bold !important;} 
   
.External_link{
  border-radius: 5px;
  border: none;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  width: 60px;
}

#project-summary {
 width: 115%; margin-left: -50px;
}

#publication {
 width: 115%; margin-left: -50px;
}

</style>

<div style="width: 115%; margin-left: -50px;">
# The temporal dynamics of plant-soil microbe interactions─effects on soil microbial communities and seedling performance
</div>

<br>

## Project Summary
<div style="height: 0.25em;"></div>

Plant-soil feedback (PSF), the reciprocal interactions between plants and soil microbes, can substantially shape the structure of plant communities. Plants condition the soil by building up parasitic or mutualistic soil microbes in the rhizosphere, which then feeds back to the growth of nearby and newly-colonized individuals. Previous studies have shown that the strength of PSF can vary throughout the development of plants (i.e., PSF changes with the duration of soil conditioning). However, the decay trajectory of PSF (i.e., how the strength of PSF changes following plant death) is currently underexplored, and empirical results remain largely lacking.

<div style="height: 1em;"></div>

To address this gap, we studied the decay trajectory of PSF and the effects of decay time on plant-soil microbe interactions. Specifically, we asked:

(1) What is the successional dynamics of soil microbial communities after plant death? Will microbial communities revert to the unconditioned states, or will they undergo different successional trajectories depending on the duration of decay process?
(2) How do microbial effects on plant growth performance change throughout the decay process after plant death? Will the effects become more neutral over time if the microbial communities gradually break down, or will the effects become more positive/negative if the microbial communities exhibit different successional trajectories?

<div style="height: 1em;"></div>

Fushan Forest Dynamics Plot is a subtropical lowland forest located in northern Taiwan. Four forest inventories have been completed since 2004, providing a unique opportunity to study the decay trajectory of PSF because these inventories allow us to trace back the decay histories of individual trees. Focusing on two tree species (*Machilus zuihoensis* and *Engelhardtia roxburghiana*) at Fushan, we collected soil samples from individuals with different durations of death and analyzed their soil microbial communities via high-throughput sequencing. We also conducted greenhouse experiments to examine microbial effects on the seedling performance of conspecifics and heterospecifics throughout the decay trajectory. We are currently analyzing the data and writing up the results. So stay tuned!

<div style="height: 1em;"></div>

Understanding PSF is critical for predicting how soil microbes influence plant communities in their natural contexts, and we hope this study can shed light on the temporal decay trajectory of plant–soil microbe interactions, thereby providing novel insights into vegetation regeneration and plant community dynamics.


<br>

<!-- ## Publication -->
<!-- <div style="height: 0.25em;"></div> -->



