---
title: "&nbsp;"
output:
  html_document:
    theme: yeti
    highlight: textmate
    css: [../../css/Research.css, ../../css/navbar.css, ../../css/body.css]
    includes:
      in_header: ../../heros/Research_hero.html
      after_body: ../../footer.html
---

<style>
h1 {text-align: center !important; 
   font-weight: bold !important; 
   font-size: 36px !important;
   line-height: 1.5em;}
   
h2 {font-weight: bold !important;} 
   
.External_link{
  border-radius: 5px;
  border: none;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  width: 60px;
}

</style>

<div>
# Effects of methyl jasmonate seed treatments on the performance of seed corn maggot
</div>

<br>

## Project Summary
<div style="height: 0.25em;"></div>

Using exogenous plant hormones to induce host plant resistance to insect herbivory is a promising approach to pest control. In particular, jasmonic acid (JA) and its derivative methyl jasmonate (MeJA) are key pheromones involved in the plant signaling pathways upon herbivory. Therefore, treating seeds with these compounds to prime plant defenses can potentially improve plant growth and crop yield by reducing pest damage.

<div style="height: 1em;"></div>

Seed corn maggot (_Delia platura_) is a severe pest of corn (_Zea mays_), especially during the seed germination and seedling stage. To examine whether MeJA seed treatment can be an effective measure for managing seed corn maggot, we treated corn seeds with different concentrations of MeJA and performed a set of choice and no-choice bioassays in both the lab and field conditions to examine how MeJA seed treatments may affect plant performance (seed germination rates and seedling growth) as well as seed corn maggot larval survival and adult oviposition preference.

<div style="height: 1em;"></div>

Our results showed that corn seeds treated with the 0.2 mM MeJA solution, despite slight reduction in seedling growth, had lower adult fly oviposition (lower number of eggs) compared to the water-treated seeds both in the lab and in the field. Moreover, larval survival to pupation was lower on MeJA-treated seeds. Lastly, the MeJA-induced resistance also occurred at the lower temperatures (15°C) typical of the spring soil conditions when the fly is most active and damaging. 

<div style="height: 1em;"></div>

Overall, our study shows that MeJA corn seed treatments can reduce larval performance and deter adult fly oviposition in spring temperature conditions with minor effects on seed germination and growth. This is exciting and promising, and further studies scaling up the experimental results to the field will help assess whether this method can serve as a practical pest management approach.

<br>

## Publication
<div style="height: 0.25em;"></div>

<p>Ray, S., <b><u>G-C. Hsu</u></b>, N.T. Pappous, O. Rooney, A.G. Taylor, and J.S. Thaler. 2024. Effects of methyl jasmonate seed treatments on adult oviposition preference and larval performance of seed corn maggot (*Delia platura*) in corn (*Zea mays*). <i>**Pest Management Science**</i>. (in press). <a href="https://doi.org/10.1002/ps.8392" target="_blank"> https://doi.org/10.1002/ps.8392</a></p>


