---
title: "&nbsp;"
output:
  html_document:
    theme: yeti
    highlight: textmate
    css: [../css/Research.css, ../css/navbar.css, ../css/body.css]
    includes:
      in_header: ../heros/Research_hero.html
      after_body: ../footer.html
---

<style>
h1 {text-align: center !important; 
   font-weight: bold !important; 
   font-size: 38px !important;
   line-height: 1.5em;}
   
h2 {font-weight: bold !important;} 
   
.External_link{
  border-radius: 5px;
  border: none;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  width: 60px;
}

#agroecology {
 width: 115%; margin-left: -55px;
}

</style>

# Agroecology

<br>

*	Crop-pest-enemy tri-trophic interactions in the face of climate change: How will climate change affect pest damage and crop production via alteration of traits and performance of crop plants, pest herbivores, and natural enemies?

<div style="height: 0.1em;"></div>

*	Interactions among different guilds of predators: How do different guilds of predators interact to regulate pest populations? In what contexts will their effects be additive, synergistic, and antagonistic?

<div style="height: 0.1em;"></div>

*	The role of alternative prey in enemy-pest interactions: What is the optimal density of alternative prey for achieving the best pest suppression outcome?

<div style="height: 0.1em;"></div>

*	Effects of farmland characteristics on pest control: How do various farmland characteristics (farm edge-to-area ratios, hedgerow and surrounding vegetation, etc.) affect species communities and interactions, pest control, and crop production?

<div style="height: 0.1em;"></div>

*	Chemical ecology in agro-ecosystems: How can plant volatiles and predator odors be applied in the field to enhance pest control?






