---
title: "&nbsp;"
output:
  html_document:
    theme: yeti
    highlight: textmate
    css: [../css/Research.css, ../css/navbar.css, ../css/body.css]
    includes:
      in_header: ../heros/Research_hero.html
      after_body: ../footer.html
---

<style>
h1 {text-align: center !important; 
   font-weight: bold !important; 
   font-size: 38px !important;
   line-height: 1.5em;}
   
h2 {font-weight: bold !important;} 
   
.External_link{
  border-radius: 5px;
  border: none;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  width: 60px;
}

</style>

# Climate Change Ecology

<br>

*	Impacts of multiple stressors on organisms: How do multiple climate change variables (temperature, precipitation, CO~2~, etc.) jointly affect species performance and interactions as well as community structures and ecosystem functioning?

<div style="height: 0.1em;"></div>

*	Integrating biological responses to temperature warming across levels of biological organization: How can warming-induced changes in individuals’ traits and species interactions be scaled up to predict population dynamics and community structures?

<div style="height: 0.1em;"></div>

*	Effects of temperature variation and extremes on biological responses: What is the importance of temperature variation and extremes in determining species performance and fitness consequences?

<div style="height: 0.1em;"></div>

*	Novel interactions and mismatches: How will climate-induced phenological and geographical shifts in organisms affect their temporal and spatial synchrony/asynchrony and in turn result in novel interactions and mismatches?

<div style="height: 0.1em;"></div>

* Chemical ecology under climate change: How will climate change affect chemical communications between and among plants, herbivores, and natural enemies and in turn their trophic interactions?

<div style="height: 0.1em;"></div>

* The role of phenotypic plasticity in buffering short-term and long-term environmental changes: Does short-term acclimation via phenotypic plasticity facilitate or impede long-term adaptation via evolutionary changes?




