---
title: "&nbsp;"
output:
  html_document:
    theme: yeti
    highlight: textmate
    css: [../css/Research.css, ../css/navbar.css, ../css/body.css]
    includes:
      in_header: ../heros/Research_hero.html
      after_body: ../footer.html
---

<style>
h1 {text-align: center !important; 
   font-weight: bold !important; 
   font-size: 38px !important;
   line-height: 1.5em;}
   
h2 {font-weight: bold !important;} 
   
.External_link{
  border-radius: 5px;
  border: none;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  width: 60px;
}

#food-web-dynamics {
 width: 115%; margin-left: -55px;
}

</style>

# Food Web Dynamics

<br>

*	Bottom-up and top-down control in food web dynamics: What is the relative importance of bottom-up vs. top-down forces, and how do these two forces interact to shape food web structures? 

<div style="height: 0.1em;"></div>

*	Trophic downgrading and upgrading: How do trophic manipulations at higher levels alter community processes and ecosystem functions such as primary productivity, nutrient cycling, and carbon storage?

<div style="height: 0.1em;"></div>

*	Interactions between food webs in different habitats: How do external resources such as spatial subsidies and allochthonous inputs influence trophic dynamics in the focal habitat?

<div style="height: 0.1em;"></div>

*	Plant-herbivore-predator-detritivore multi-trophic interactions: How do above-ground grazing food webs and below-ground detritus food webs interact and feed back to each other?



