---
title: "&nbsp;"
output:
  html_document:
    theme: yeti
    highlight: textmate
    css: [../css/Research.css, ../css/navbar.css, ../css/body.css]
    includes:
      in_header: ../heros/Research_hero.html
      after_body: ../footer.html
---

<style>
h1 {text-align: center !important; 
   font-weight: bold !important; 
   font-size: 36px !important;
   line-height: 1.5em;}
   
h2 {font-weight: bold !important;} 
   
.External_link{
  border-radius: 5px;
  border: none;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  width: 60px;
}
</style>

# Species Interactions/Trophic Ecology

<br>

* __Species Interactions and Trophic Ecology:__ 
  - Quantifying the relative importance of top-down vs. bottom-up forces in governing the dynamics of food webs involving multi-trophic interactions and feedback/feed-forward processes
  - How within-trophic-level interactions (e.g., competition and intra-guild predation) affect among-trophic-level interactions (e.g., plant-herbivore and predator-prey) as well as their ecological consequences for population dynamics
  - What factors determine the resource use and diet compositions of generalist predators—developmental stage, prey preference, foraging mode, prey availability, inter- and intra-specific competition, environmental conditions, etc.   
  - How assemblages of predators interact to exert consumptive and non-consumptive effects on prey and subsequently influence predator-prey eco-evolutionary dynamics, and how the relative importance of consumptive vs. non-consumptive effects varies with abiotic and biotic conditions. 










