---
title: "&nbsp;"
output:
  html_document:
    theme: yeti
    highlight: textmate
    css: [../css/Research.css, ../css/navbar.css, ../css/body.css]
    includes:
      in_header: ../heros/Research_hero.html
      after_body: ../footer.html
---

<style>
h1 {text-align: center !important; 
   font-weight: bold !important; 
   font-size: 36px !important;
   line-height: 1.5em;}
   
h2 {font-weight: bold !important;} 
   
.External_link{
  border-radius: 5px;
  border: none;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  width: 60px;
}
</style>

# Trophic Ecology

<br>

* Resource use and diet compositions of generalist predators—developmental stage, prey preference, foraging mode, prey availability, inter- and intra-specific competition, environmental conditions, etc.

<div style="height: 0.1em;"></div>

* Patterns and impacts of trophic omnivory, intraguild predation, and cannibalism in global ecosystems 

<div style="height: 0.1em;"></div>

* Relative strengths of top-down vs. bottom-up forces in governing food web dynamics

<div style="height: 0.1em;"></div>

* Trophic downgrading and upgrading: food web manipulations (e.g., resource subsidies and shunts, predator removal or addition)





