---
title: "&nbsp;"
output:
  html_document:
    theme: yeti
    highlight: textmate
    css: [../css/Research.css, ../css/navbar.css, ../css/body.css]
    includes:
      in_header: ../heros/Research_hero.html
      after_body: ../footer.html
---

<style>
h1 {text-align: center !important; 
   font-weight: bold !important; 
   font-size: 38px !important;
   line-height: 1.5em;}
   
h2 {font-weight: bold !important;} 
   
.External_link{
  border-radius: 5px;
  border: none;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  width: 60px;
}

#trophic-interactions {
 width: 115%; margin-left: -50px;
}

</style>

# Trophic Interactions

<br>

*	Mechanisms underlying the diet compositions of consumers: What are the roles of resource availability, resource attractiveness and preference, energy and nutritional requirement, foraging behavior and hunting mode, immediate and potential predation risk, and developmental stage in determining dietary patterns of consumers?

<div style="height: 0.1em;"></div>

* Ecology of various types of plant defense mechanisms against herbivores: What biotic and abiotic factors determine the relative importance of physical vs. chemical, direct vs. indirect, and induced vs. constitutive plant defense? 
<div style="height: 0.1em;"></div>

*	The role of consumptive vs. non-consumptive predator effects on predator-prey interactions: What are the relative strengths of density-, physiology-, and behavior-mediated trophic interactions in governing predator-prey population dynamics?

<div style="height: 0.1em;"></div>

*	Multiple drivers of non-consumptive predator effects: What abiotic and biotic factors may influence the strength of non-consumptive predator effects? How can we integrate resource landscape, thermal landscape, and landscape of fear (evasion landscape & encounter landscape) to predict non-consumptive predator-prey interactions?

<div style="height: 0.1em;"></div>

* Plant-herbivore-predator tri-trophic triangles: How can we shift from the traditional chain-perspective of plant-herbivore-predator tri-trophic interactions to the modern network-perspective of tri-trophic triangles?

<div style="height: 0.1em;"></div>

*	Intraguild predation, omnivory, and cannibalism of organisms: What are the patterns of intraguild predation, omnivory, and cannibalism in different types of ecosystems and their impacts on food web dynamics?







