---
title: "&nbsp;"
output:
  html_document:
    theme: yeti
    highlight: textmate
    css: [../../css/Research.css, ../../css/navbar.css, ../../css/body.css]
    includes:
      in_header: ../../heros/Research_hero.html
      after_body: ../../footer.html
---

<style>
h1 {text-align: center !important; 
   font-weight: bold !important; 
   font-size: 36px !important;
   line-height: 1.5em;}
   
h2 {font-weight: bold !important;} 
   
.External_link{
  border-radius: 5px;
  border: none;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  width: 60px;
}

</style>

<div>
# Quantifying the diet compositions of generalist arthropod predators in rice agro-ecosystems
</div>

<br>

## Project Summary
<div style="height: 0.25em;"></div>

Generalist arthropod predators (GAPs) are ubiquitous in agro-ecosystems and play a critical ecological role in food web dynamics. GAPs have been used as biocontrol agents; however, because of their polyphagous nature, these predators may feed on not only the target pests but also the alternative prey. As a result, there is much concern about whether these predators can provide effective biocontrol services in agro-ecosystems. Such a concern necessitates a better understanding of the trophic interactions between GAPs and their prey in the field.    

<div style="height: 1em;"></div>
We sampled arthropod communities in rice farms in central Taiwan, 
analyzed their stable isotope signatures, and used the Bayesian stable isotope mixing models to quantify the diet compositions of GAPs (spiders and ladybeetles) from different prey sources (rice pests, tourist herbivores, and detritivores).

<div style="height: 1em;"></div>

We found that GAPs in both organic and conventional farms consumed increasing proportion of rice pests in their diets over the crop season (rice pests accounted for over 90% of GAPs' diet at the ripening stage). Surprisingly, our results show that GAPs in conventional farms consumed higher proportion of rice pests compared with GAPs in organic farms. Moreover, we also found a positive relationship between the relative abundance of rice pests in the field and the proportion of rice pests consumed in GAPs' diet. This suggests that GAPs can increase their consumption on pests when pest populations build up.

<div style="height: 1em;"></div>

Our findings demonstrate the strong per capita consumption effect of GAPs on pests, highlighting their promising potential as biocontrol agents. The next important step is to combine multiple approaches (e.g., field observations, manipulative experiments, and molecular gut content analysis) to gain a deeper insight into the complex predator-prey trophic dynamics in agro-ecosystems.

<br>

## Publication
<div style="height: 0.25em;"></div>

<p><b><u>Hsu, G-C.</u></b>, J-A. Ou, and C-K. Ho. 2021. Pest consumption by generalist arthropod predators increases with crop stage in both organic and conventional farms. <i>Ecosphere</i> 12(7): e03625. <a href="https://doi.org/10.1002/ecs2.3625" target="_blank"> https://doi.org/10.1002/ecs2.3625</a></p>

<p><b><u>Hsu, G-C.</u></b>, J-A. Ou, M-H. Ni, Z-H. Lin, and C-K. Ho. 2025. Generalist predators function as pest specialists: examining diet composition of spiders and ladybeetles across rice crop stages. <i>*Journal of Applied Ecology*</i>. (accepted)</p> <!-- <a class="External_link btn btn-primary btn-outline btn-xs" href="https://doi.org/10.1101/2022.01.31.478501" target="_blank">Preprint</a> -->
<!-- <a class="External_link btn btn-primary btn-outline btn-xs" href="https://github.com/GenChangHSU/2022_Earthworm_Stable_Isotope_Niche" target="_blank">GitHub</a> -->








