---
title: "&nbsp;"
output:
  html_document:
    theme: yeti
    highlight: textmate
    css: [../../css/Research.css, ../../css/navbar.css, ../../css/body.css]
    includes:
      in_header: ../../heros/Research_hero.html
      after_body: ../../footer.html
---

<style>
h1 {text-align: center !important; 
   font-weight: bold !important; 
   font-size: 36px !important;
   line-height: 1.5em;}
   
h2 {font-weight: bold !important;} 
   
.External_link{
  border-radius: 5px;
  border: none;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  width: 60px;
}

</style>

<div>
# Temporal trends in academic performance and career duration of principal investigators in ecology and evolutionary biology in Taiwan
</div>

<br>

## Project Summary
<div style="height: 0.25em;"></div>

Academic job markets have become increasingly challenging worldwide. There are more and more PhDs and postdocs produced each year, yet the number of faculty positions remains relatively unchanged. Despite the general notion that applicants face increasing competition for limited opportunities, few studies have actually quantitatively examined how research performance and other determinants of academic success, including PhD university origin, prestige, and gender, affect recruitment and promotion over time.

<div style="height: 1em;"></div>

To this end, we collected data on the academic performance (measured as h-index), year of recruitment and promotion, PhD granting university, and gender of 145 principal investigators (PIs) in the field of ecology and evolutionary biology in Taiwan over the past 34 years. We examined how the academic performance of PIs changed over time, and how PhD university and gender affected their performance. We also examined how the duration before recruitment and promotion changed over time, and how academic performance, PhD university, and gender affected their career duration.

<div style="height: 1em;"></div>

We found that the performance of PIs during the recruitment and promotion stage both increased in recent years, indicating that the performance requirements have become higher over time. We also found that male PIs had on average higher performance than female PIs during the recruitment stage. Moreover, the career duration before recruitment and before promotion both increased in recent years, suggesting that the applicants spent on average a longer period of time before landing a job or getting a promotion. Interestingly, PIs with Taiwanese PhD degrees tended to have longer duration before recruitment compared to those with foreign degrees, whereas PhD university ranking had no effect on either academic performance or career duration.

<div style="height: 1em;"></div>

Taken together, our study confirms that succeeding in academia has become more challenging, with performance requirements and career duration both increasing over years (at least in the field of EEB in Taiwan). Regardless of which career stage you are at, which university you received you PhD degree, and which gender you are, boosting research performance is the ultimate key to academic success in the face of increasingly competitive academic job markets.

<br>

## Publication
<div style="height: 0.25em;"></div>

<p><b><u>Hsu, G-C.</u></b>, W-J. Lin, and S-J. Sun. 2023. Temporal trends in academic performance and career duration of principal investigators in ecology and evolutionary biology in Taiwan. <i>Scientometrics</i> 128: 3437–3451.
<a href="https://doi.org/10.1007/s11192-023-04710-9" target="_blank"> https://doi.org/10.1007/s11192-023-04710-9</a></p>


